### PR TITLE
Bump dependencies and Rust edition

### PR DESCRIPTION
**Pull request by Speykious**
This PR lets miniquad use the latest versions of all dependencies and the latest Rust edition.
On my Linux machine, the compile times haven't really been affected, so it shouldn't cause any additional problems.

`glam` doesn't need to have any additional features, and now also has a bunch more QOL functions that miniquad examples could use a bit everywhere, such as doing some `Vec2 / f32` operations, though it's probably better to keep that for a separate PR.

As for `ndk-sys` going from 0.2 to 0.4, I have tested it on my phone and examples just crash on startup. I don't know what to do nor why it happens despite the logs, so I'm not bumping it.

Otherwise, all other dependencies are up-to-date on their major version.

### CODE REVIEW

**Comment by Speykious** [comment]
Not sure what's causing this...

App not installed as package appears to be invalid.

**Comment by FaunKr** [comment]
> Not sure what's causing this...
> 
> App not installed as package appears to be invalid.

Which android version are you using for testing?

**Comment by Speykious** [comment]
> > Not sure what's causing this...
> > App not installed as package appears to be invalid.
> 
> Which android version are you using for testing?

My own phone is Android 13, I create the apk with docker

**Comment by FaunKr** [comment]
Try to add

**Comment by Speykious** [comment]
> Try to add to the cargo.toml. That resolves it for me
> 
> ```
> [package.metadata.android.activity_attributes]
> "android:exported" =  "true"
> ```
> 
> Edit: This is caused because Android 12 & 13 expects the main activity to have the [exported attribute set explicitly](https://stackoverflow.com/a/67412314) which miniquad/[cargo-quad-apk](https://github.com/not-fl3/cargo-quad-apk) doesn't do by default.

Indeed, after a bit of searching I came to the same conclusion (and not-fl3 too on Discord).
Should I commit this here too? Will miniquad projects be able to override it?

**Comment by Speykious** [comment]
On the other hand, I got a crash when trying to launch the application...
Here are all the lines of logs related to the blobs example running on my phone.
```
02-09 23:09:49.157  1801 25202 W OplusEapManager handleErrorInfo sendEvent: : rust.miniquad.example.blobs Crashed
02-09 23:09:49.162  3660  3688 D abnormalUtils: rust.miniquad.example.blobs is foreground =true
02-09 23:09:49.163  1801 25202 W ActivityTaskManager:   Force finishing activity rust.miniquad.example.blobs/.MainActivity
02-09 23:09:49.165  1580  1580 D OplusLayer: ~Layer() sequence=21820, name=ca596be Splash Screen rust.miniquad.example.blobs#21820
02-09 23:09:49.166  1801 25202 V OplusZoomWindowManagerService: prepareZoomTransition: curStack=Task{7335d97 #2000 type=standard A=10121:rust.miniquad.example.blobs U=0 visible=false visibleRequested=true mode=fullscreen translucent=true sz=1}   nextStackTask{53b327a #1 type=home ?? U=0 visible=true visibleRequested=false mode=fullscreen translucent=true sz=1}
02-09 23:09:49.173  1365  1478 E ANDR-PERF-LM: GamePerfEngine: runAsync() 499: Hint is for rust.miniquad.example.blobs/rust.miniquad.example.blobs.MainActivity/1 = 0x1004 PID=1801
02-09 23:09:49.173  1365  1478 W ANDR-PERF-LM: MetaMeter: handleAsync() 171: GameOptimization Invalid state for appName rust.miniquad.example.blobs 
02-09 23:09:49.185  1580  1676 I SurfaceFlinger: [SF client] REMOVE (0xb40000731bb31bc0) for (25055:rust.miniquad.example.blobs)
02-09 23:09:49.185  1801  7482 I ActivityManager: Process rust.miniquad.example.blobs (pid 25055) has died: fg  TOP 
02-09 23:09:49.185  1801  7482 D OplusUIFirst_FB: rust.miniquad.example.blobs remove pid: 25055
02-09 23:09:49.186  1801  7482 D OplusStartingWindowManager: interceptRemoveStartingWindow: packageName=rust.miniquad.example.blobs, isSnapshot=false, startingSurfaceRunnable=null
02-09 23:09:49.186  1801  7482 I OplusHansManager : front pkg: com.android.launcher, uid: 10109, prev pkg: rust.miniquad.example.blobs, prev uid: 10121
02-09 23:09:49.187  1801  4333 I OplusHansManager : uid=10121, pkg=rust.miniquad.example.blobs enter SM
02-09 23:09:49.187  1801  4333 I OplusHansManager : uid=10121, pkg=rust.miniquad.example.blobs R enter(), D stay=0
02-09 23:09:49.187  1801  3517 I Osense-DecisionMaker: notifySceneToAthenaPolicy: SCENE_LAUNCHER, bundle: Bundle[{prevPkgName=rust.miniquad.example.blobs, curUid=10109, curPkgName=com.android.launcher, prevUid=10121}]
02-09 23:09:49.188  1801  4357 I OplusResourcePreloadManager: resume pkg: com.android.launcher, uid:10109, prev pkg: rust.miniquad.example.blobs, prev uid: 10121
02-09 23:09:49.191  1801  4501 I OplusHansManager : onUidGone(), 10121 rust.miniquad.example.blobs exit SM
02-09 23:09:49.191  1801  4333 I OplusHansManager : uid=10121, pkg=rust.miniquad.example.blobs R exit SM
02-09 23:09:49.191  1801  4333 I OplusHansManager : uid=10121, pkg=rust.miniquad.example.blobs R exit(), R stay=0
02-09 23:09:49.230  1801  5000 V OplusZoomWindowManagerService: onAnimationFinished:  r = ActivityRecord{2f870bb u0 rust.miniquad.example.blobs/.MainActivity} t2000 f} isExiting}
02-09 23:09:49.230  1801  5000 I WindowStateExtImpl: onSurfaceShowChange show = false mPackageName = rust.miniquad.example.blobs parentPkgName = rust.miniquad.example.blobs
02-09 23:09:49.231  1801  5000 W InputManager-JNI: Input channel object 'de8471c Splash Screen rust.miniquad.example.blobs (client)' was disposed without first being removed with the input manager!
02-09 23:09:49.231  1580  1580 D Layer   : reparent to null sequence=21835, seq[5], name=Splash Screen rust.miniquad.example.blobs#21835
```

**Comment by Speykious** [comment]
I've reverted my ndk-sys version bump. Android programs crash on the latest version, so better stay on 0.2 for now.
Once all tests pass this PR can probably be merged.

**Comment by Speykious** [comment]
I'll close this PR, it's so behind that I'd rather rewrite it given the small amount of changes.

**Pull request closed without merging**
